channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >= 3.10
  - pip
  - setuptools_scm
  - toml

  # Documentation
  - furo
  - ipython
  - nbsphinx
  - myst-parser
  - sphinx
  - sphinx-design
  - sphinx-copybutton

  - pip:
    - ../
    - sphinxext-opengraph
