exclude: |
    (?x)^(
        {{cookiecutter.project_slug}}/tests/test_import.py
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=25']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
        exclude:  |
            (?x)^(
                {{cookiecutter.project_slug}}/environment.yml|
                {{cookiecutter.project_slug}}/.pre-commit-config.yaml
            )$
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char
-   repo: https://github.com/aio-libs/sort-all
    rev: v1.2.0
    hooks:
    -   id: sort-all
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--config, pyproject.toml, hooks, tests]
        pass_filenames: false
      - id: ruff-format
        args: [--config, pyproject.toml]
-   repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
    -   id: refurb
        exclude: ({{cookiecutter.project_slug}})
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-gfm,
            mdformat-black,
        ]
        args: [--wrap, "88"]
        files: (README\.md)
        exclude: |
          (?x)^(
              {{cookiecutter.project_slug}}/README.md
          )$
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-myst,
            mdformat-black,
        ]
        args: [--wrap, "88"]
        files: (docs/.)
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        additional_dependencies: [tomli]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
    -   id: mypy
        pass_filenames: false
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
