name: cp

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.7
  - pip >=21.1
  - setuptools_scm
  - toml

  # Package dependencies
  - cookiecutter
  - pytask >=0.1.7

  # Misc
  - black
  - ipython
  - mypy
  - pre-commit
  - pytest
  - pytest-cookies
  - pytest-cov
  - pytest-xdist
  - tox-conda

  # Documentation
  - furo
  - myst-parser
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-panels

  - pip:
    - ../
    - sphinxext-opengraph
